(define (calc)
  (newline)
  (display "calc:")
  (newline)
  (display (calc-eval (read)))
  (calc))
(define (calc-eval exp)
  (cond ((number? exp) exp)
        ((list? exp) (calc-apply (car exp) (map calc-eval (cdr exp))))
        (else (display "calc: bad expression"))))
(define (calc-apply fn args)
  (cond ((eq? fn '+) (+ (car args) (car (cdr args))))
        (else (display "bad function"))))
